version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/uzairalikhan/redus-dump
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u golang.org/x/lint/golint
      - run: golint -set_exit_status ./.../
      - run: go build redis-dump.go